# -*- coding: UTF-8 -*-

SECRET_KEY = ''
SQLALCHEMY_DATABASE_URI = ''
CELERY_BROKER_URL = ''
CELERY_RESULT_BACKEND = ''
USER_AGENT_FILE = ''
GITHUB_CONSUMER_KEY = ''
GITHUB_CONSUMER_SECRET = ''
FLASK_DONATE_WECHAT_IMAGE = ''
FLASK_DONATE_ALIPAY_IMAGE = ''
SQLALCHEMY_TRACK_MODIFICATIONS = False
FLASK_CHANNEL_PER_PAGE = 60
FLASK_ROOM_PER_PAGE = 40
FLASK_ROOMDATA_PER_PAGE = 40
FLASK_ROOM_RANK_NUM = 15
FLASK_CHANNEL_RANK_NUM = 15
FLASK_SEARCH_PER_PAGE = 8
SESSION_PROTECTION = 'strong'
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IGNORE_RESULT = True
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC=True
RESTFUL_JSON = {
    'ensure_ascii': False
}
