# -*- coding: UTF-8 -*-
SECRET_KEY = ''
SQLALCHEMY_DATABASE_URI = ''
CELERY_BROKER_URL = ''
USER_AGENT_FILE = ''
SQLALCHEMY_TRACK_MODIFICATIONS = False
FLASK_CHANNEL_PER_PAGE = 60
FLASK_ROOM_PER_PAGE = 40
FLASK_ROOMDATA_PER_PAGE = 40
FLASK_ROOM_RANK_NUM = 15
FLASK_CHANNEL_RANK_NUM = 15
FLASK_SEARCH_PER_PAGE = 8
SESSION_PROTECTION = 'strong'
RESTFUL_JSON = {
    'ensure_ascii': False
}
